# start FROM a base layer of postgres 13.4
FROM postgres:13.4

# copy in ./scripts/db_init.sql to /docker-entrypoint-initdb.d/  
# It will run automatically from within the container to 
# build out our own personal test database.
COPY ./scripts/db_init.sql /docker-entrypoint-initdb.d/